stages:
- build

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script: 
    - mvn clean package
    - rm /builds/Songoda/EpicSpawners/EpicSpawners-Plugin/*original*
    - mv -v /builds/Songoda/EpicSpawners/EpicSpawners-Plugin/target/* /builds/Songoda/EpicSpawners/
  artifacts:
    name: "EpicSpawners"
    paths:
    - "/builds/Songoda/EpicSpawners/*.jar"
    - "/builds/Songoda/EpicSpawners/Read_this_before_your_first_use.txt"
